### ISSUE TITLE
AttributeError: 'BlockDeviceMapping' object has no attribute 'autoscale_build_list_params'

### ISSUE THREAD

**Issue by ghost** [boto/boto#2503]
boto: 2.32.0
python: 2.7.5

When I pull down an existing launch configuraiton from AWS using https://boto.readthedocs.org/en/2.2.2/ref/autoscale.html#boto.ec2.autoscale.AutoScaleConnection.get_all_launch_configurations, I thought that I would be able to change the name, change some other attributes and then call https://boto.readthedocs.org/en/2.2.2/ref/autoscale.html#boto.ec2.autoscale.AutoScaleConnection.create_launch_configuration and create another launch config in AWS. However, upon doing so I get a

```
/Users/twork/.virtualenvs/my_project/bin/python /Users/twork/my-project/update.py
Traceback (most recent call last):
  File "/Users/twork/my-project/update.py", line 5, in <module>
    asgm.update_autoscaling_group('ami-0asd8251', 'new tag!')
  File "/Users/twork/my-project/my_project/auto_scaling_groups_manager.py", line 68, in update_autoscaling_group
    self.autoscale_connection.create_launch_configuration(new_launch_config)
  File "/Users/twork/.virtualenvs/my_project/lib/python2.7/site-packages/boto/ec2/autoscale/__init__.py", line 231, in create_launch_configuration
    [x.autoscale_build_list_params(params) for x in launch_config.block_device_mappings]
AttributeError: 'BlockDeviceMapping' object has no attribute 'autoscale_build_list_params'
```

I'm assuming this has something to do with the comment at the top of the class definition for BlockDeviceMapping() in ec2/autoscale/launchconfig.py

```
# this should use the BlockDeviceMapping from boto.ec2.blockdevicemapping
# Currently in use by deprecated code for backwards compatability
# Removing this class can also remove the Ebs class in this same file
```

but I can't say for sure.

**Comment by haren** [comment]
Doesn't work with boto 2.38.0. Did work with boto 2.9.x. My code snippet:

```
def create_launch_configuration_from_config_obj(
	autoscale_connection, launch_config_obj
	):
        pprint(launch_config_obj.__dict__)
	autoscale_connection.create_launch_configuration(
		launch_config_obj
	)
	return get_launch_configurations_for_connection(
		autoscale_connection, names=[launch_config_obj.name]
	)
``` 

`pprint` prints out this:
```
{'associate_public_ip_address': None,
 'block_device_mappings': [[BlockDeviceMapping(/dev/sda1, None)]],
 'classic_link_vpc_id': None,
 'classic_link_vpc_security_groups': [],
 'connection': AutoScaleConnection:autoscaling.eu-west-1.amazonaws.com,
 'created_time': datetime.datetime(2015, 6, 18, 14, 53, 45, 662000),
 'delete_on_termination': True,
 'ebs_optimized': False,
 'image_id': u'ami-41807c2a',
 'instance_monitoring': InstanceMonitoring(false),
 'instance_profile_name': None,
 'instance_type': u't1.micro',
 'iops': None,
 'kernel_id': '',
 'key_name': u'lukasz',
 'launch_configuration_arn': u'arn:aws:autoscaling:eu-west-1:018008385220:launchConfiguration:18176cb9-0be2-44b6-aa76-7f8f26965250:launchConfigurationName/im-client-test-launch-config',
 'member': u'\n      ',
 'name': u'im-client-test-launch-config',
 'ramdisk_id': '',
 'security_groups': [u'sg-584aa63f'],
 'spot_price': None,
 'use_block_device_types': False,
 'user_data': '',
 'volume_type': None}
```

**Comment by jamescarr** [comment]
I am also hitting this problem with `2.38.0` as well. Here's my code in it's entirety, all we are doing here is creating a new launch_config based off the previous one with just an updated AMI. 


```python

@task
def update_ami(autoscaling_group_name, ami):
    '''
    e.g. autoscaling_group_name=asg-worker-email,ami=ami-12345
    '''
    import boto
    import time
    from boto.ec2.autoscale import AutoScaleConnection
    from boto.ec2.autoscale.launchconfig import LaunchConfiguration
    conn = boto.connect_autoscale(use_block_device_types=True)
    asg = None
    tag = int(time.time())
    asg_name = 'asg-{}'.format(autoscaling_group_name)

    groups = conn.get_all_groups()

    for group in groups:
        if group.name.startswith(asg_name):
            asg = group
            break
    if not asg:
        raise Exception("No ASG named {} found!".format(asg_name))

    print(asg.launch_config_name)
    lc = conn.get_all_launch_configurations(names=[asg.launch_config_name]).pop()

    print("Current launch_config {} is using ami {}".format(lc, lc.image_id))

    new_lc = LaunchConfiguration(
        image_id=ami,
        name='{}-{}'.format(autoscaling_group_name, tag),
        key_name=lc.key_name,
        security_groups=lc.security_groups,
        user_data=lc.user_data,
        instance_type=lc.instance_type,
        kernel_id=lc.kernel_id,
        ramdisk_id=lc.ramdisk_id,
        block_device_mappings=lc.block_device_mappings,
        instance_monitoring=lc.instance_monitoring,
        instance_profile_name=lc.instance_profile_name,
        ebs_optimized=lc.ebs_optimized,
        associate_public_ip_address=lc.associate_public_ip_address,
    )

    print("Creating new launch_config {} with ami {}".format(new_lc, new_lc.image_id))
    
    result = conn.create_launch_configuration(new_lc)
    
    asg.launch_config_name = new_lc.name;
    print("Updating {} to use {}".format(asg.name, new_lc.name))
    asg.update()

```

Here I get `AttributeError: 'unicode' object has no attribute 'autoscale_build_list_params'`.

If I set `use_block_device_types=False` then I get:

`AttributeError: 'BlockDeviceMapping' object has no attribute 'autoscale_build_list_params'`

What gives here!?

**Comment by yardensachs** [comment]
@jamescarr here is the fix:
new_lc.block_device_mappings = [new_lc.block_device_mappings]

**Comment by blacked** [comment]
Thanks @yardensachs, your fix works well for me!

**Comment by zerOnepal** [comment]
Since we have it fixed on new boto, can we close this. :neutral_face: 
thanks
